- pkg:maven/com.infobip.kafkistry/kafkistry-prometheus-metrics-export@0.0.4
- pkg:maven/com.infobip.kafkistry/kafkistry-prometheus-metrics-export@0.0.4?classifier=sources
- pkg:maven/com.infobip.kafkistry/kafkistry-prometheus-metrics-export@0.1.0
- pkg:maven/com.infobip.kafkistry/kafkistry-prometheus-metrics-export@0.1.0?classifier=sources
- pkg:maven/com.infobip.kafkistry/kafkistry-prometheus-metrics-export@0.1.1
- pkg:maven/com.infobip.kafkistry/kafkistry-prometheus-metrics-export@0.1.1?classifier=sources
- pkg:maven/com.infobip.kafkistry/kafkistry-prometheus-metrics-export@0.3.0
- pkg:maven/com.infobip.kafkistry/kafkistry-prometheus-metrics-export@0.3.0?classifier=sources
- pkg:maven/com.infobip.kafkistry/kafkistry-prometheus-metrics-export@0.4.0
- pkg:maven/com.infobip.kafkistry/kafkistry-prometheus-metrics-export@0.4.0?classifier=sources
- pkg:maven/com.infobip.kafkistry/kafkistry-prometheus-metrics-export@0.4.1
- pkg:maven/com.infobip.kafkistry/kafkistry-prometheus-metrics-export@0.4.1?classifier=sources
