- pkg:maven/com.frontegg.sdk/config@0.0.2
- pkg:maven/com.frontegg.sdk/config@0.0.2?classifier=sources
- pkg:maven/com.frontegg.sdk/config@0.0.3
- pkg:maven/com.frontegg.sdk/config@0.0.3?classifier=sources
- pkg:maven/com.frontegg.sdk/config@0.0.4
- pkg:maven/com.frontegg.sdk/config@0.0.4?classifier=sources
- pkg:maven/com.frontegg.sdk/config@0.0.5
- pkg:maven/com.frontegg.sdk/config@0.0.5?classifier=sources
- pkg:maven/com.frontegg.sdk/config@0.0.6
- pkg:maven/com.frontegg.sdk/config@0.0.6?classifier=sources
