- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@1.3.0
- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@1.3.0?classifier=sources
- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@1.4.2
- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@1.4.2?classifier=sources
- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@1.5.0
- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@1.5.0?classifier=sources
