- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@1.3.0
- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@1.3.0?classifier=sources
- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@1.4.2
- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@1.4.2?classifier=sources
- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@1.5.0
- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@1.5.0?classifier=sources
- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@1.7.0?classifier=sources
- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@1.8.0?classifier=sources
- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@1.9.0?classifier=sources
- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@2.0.0?classifier=sources
- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@2.1.0?classifier=sources
- pkg:maven/com.palantir.docker.compose/docker-compose-junit-jupiter@2.2.0?classifier=sources
