- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.0.2
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.0.2?classifier=sources
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.1.0
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.1.0?classifier=sources
