- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.0.2
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.0.2?classifier=sources
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.1.0
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.1.0?classifier=sources
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.1.1
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.1.1?classifier=sources
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.1.2
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.1.2?classifier=sources
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.1.3
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.1.3?classifier=sources
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.2.0
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.2.0?classifier=sources
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.2.1
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.2.1?classifier=sources
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.3.0
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.3.0?classifier=sources
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.3.1
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.3.1?classifier=sources
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.3.2
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.3.2?classifier=sources
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.3.3
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.3.3?classifier=sources
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.3.4
- pkg:maven/io.buoyant/telemetry-prometheus_2.12@1.3.4?classifier=sources
