- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.15.0
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.15.0?classifier=sources
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.10
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.10?classifier=sources
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.11
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.11?classifier=sources
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.12
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.12?classifier=sources
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.13
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.13?classifier=sources
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.14
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.14?classifier=sources
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.15
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.15?classifier=sources
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.16
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.16?classifier=sources
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.18
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.18?classifier=sources
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.9
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-example@0.17.9?classifier=sources
