- pkg:maven/io.prometheus.client.examples/random@0.0.1
- pkg:maven/io.prometheus.client.examples/random@0.0.1?classifier=sources
- pkg:maven/io.prometheus.client.examples/random@0.0.2
- pkg:maven/io.prometheus.client.examples/random@0.0.2?classifier=sources
- pkg:maven/io.prometheus.client.examples/random@0.0.3
- pkg:maven/io.prometheus.client.examples/random@0.0.3?classifier=sources
- pkg:maven/io.prometheus.client.examples/random@0.0.4
- pkg:maven/io.prometheus.client.examples/random@0.0.4?classifier=sources
