- pkg:maven/org.dmonix/prometheus-client-scala_2.12@1.0.0
- pkg:maven/org.dmonix/prometheus-client-scala_2.12@1.0.0?classifier=sources
- pkg:maven/org.dmonix/prometheus-client-scala_2.12@1.1.0
- pkg:maven/org.dmonix/prometheus-client-scala_2.12@1.1.0?classifier=sources
