- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.0
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.0-M10
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.0-M10?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.0-M11
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.0-M11?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.0-M15
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.0-M15?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.0-M17
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.0-M17?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.0-M18
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.0-M18?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.0-M8
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.0-M8?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.0-M9
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.0-M9?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.0?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.1
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.1?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.3
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.18.3?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M1
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M10
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M10?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M11
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M11?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M12
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M12?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M13
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M13?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M14
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M14?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M15
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M15?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M16
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M16?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M1?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M2
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M2?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M3
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M3?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M4
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M4?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M5
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M5?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M7
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M7?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M8
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M8?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M9
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0-M9?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.0?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.1
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.1?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.3
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.3?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.4
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.19.4?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M10
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M10?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M2
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M2?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M3
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M3?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M4
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M4?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M5
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M5?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M6
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M6?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M7
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M7?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M8
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M8?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M9
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0-M9?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.0?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.1
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.1?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.2
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@0.20.2?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M1
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M1?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M2
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M2?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M3
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M3?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M4
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M4?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M5
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M5?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M6
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M6?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M7
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M7?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M8
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M8?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M9
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-M9?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-RC1
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-RC1?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-RC2
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-RC2?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-RC3
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0-RC3?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.0?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.1
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.1?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.2
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.2?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.3
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.3?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.4
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.4?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.5
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.5?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.6
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.0.6?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.1.0
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.1.0?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.1.1
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.1.1?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.1.2
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.1.2?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.1.3
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.1.3?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.1.4
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.1.4?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.0
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.0?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.1
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.10
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.10?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.11
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.11?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.12
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.12?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.13
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.13?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.1?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.2
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.2?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.3
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.3?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.4
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.4?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.5
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.5?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.6
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.6?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.7
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.7?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.8
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.8?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.9
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.2.9?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.3.0
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.3.0?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.4.0
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.4.0?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.5.0
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.5.0?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.5.1
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.5.1?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.5.4
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.5.4?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.5.5
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.5.5?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.6.0
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.6.0?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.6.1
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.6.1?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.6.2
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.6.2?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.6.3
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.6.3?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.6.4
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.6.4?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.7.0
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.7.0?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.7.1
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.7.1?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.7.2
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.7.2?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.7.3
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.7.3?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.7.4
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.7.4?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.7.5
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.7.5?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.7.6
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.7.6?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.8.0
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.8.0?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.8.1
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.8.1?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.8.2
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.8.2?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.8.3
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.8.3?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.8.4
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.8.4?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.8.5
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.8.5?classifier=sources
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.9.0
- pkg:maven/com.softwaremill.sttp.tapir/tapir-prometheus-metrics_2.12@1.9.0?classifier=sources
