- pkg:maven/com.ibm.runtimetools/javametrics-prometheus@1.0.2?classifier=sources
- pkg:maven/com.ibm.runtimetools/javametrics-prometheus@1.0.2?type=war
- pkg:maven/com.ibm.runtimetools/javametrics-prometheus@1.1.0?classifier=sources
- pkg:maven/com.ibm.runtimetools/javametrics-prometheus@1.1.0?type=war
- pkg:maven/com.ibm.runtimetools/javametrics-prometheus@1.2.0?classifier=sources
- pkg:maven/com.ibm.runtimetools/javametrics-prometheus@1.2.0?type=war
- pkg:maven/com.ibm.runtimetools/javametrics-prometheus@1.2.1?classifier=sources
- pkg:maven/com.ibm.runtimetools/javametrics-prometheus@1.2.1?type=war
- pkg:maven/com.ibm.runtimetools/javametrics-prometheus@1.3.0?classifier=sources
- pkg:maven/com.ibm.runtimetools/javametrics-prometheus@1.3.0?type=war
- pkg:maven/com.ibm.runtimetools/javametrics-prometheus@1.3.1?classifier=sources
- pkg:maven/com.ibm.runtimetools/javametrics-prometheus@1.3.1?type=war
- pkg:maven/com.ibm.runtimetools/javametrics-prometheus@1.4.0?classifier=sources
- pkg:maven/com.ibm.runtimetools/javametrics-prometheus@1.4.0?type=war
