- pkg:maven/com.malliina/netlify_2.12@1.6.45
- pkg:maven/com.malliina/netlify_2.12@1.6.45?classifier=sources
- pkg:maven/com.malliina/netlify_2.12@1.6.46
- pkg:maven/com.malliina/netlify_2.12@1.6.46?classifier=sources
- pkg:maven/com.malliina/netlify_2.12@1.6.47
- pkg:maven/com.malliina/netlify_2.12@1.6.47?classifier=sources
- pkg:maven/com.malliina/netlify_2.12@1.6.48
- pkg:maven/com.malliina/netlify_2.12@1.6.48?classifier=sources
- pkg:maven/com.malliina/netlify_2.12@1.6.49
- pkg:maven/com.malliina/netlify_2.12@1.6.49?classifier=sources
- pkg:maven/com.malliina/netlify_2.12@1.6.54
- pkg:maven/com.malliina/netlify_2.12@1.6.54?classifier=sources
- pkg:maven/com.malliina/netlify_2.12@1.6.55
- pkg:maven/com.malliina/netlify_2.12@1.6.55?classifier=sources
