- pkg:maven/io.prometheus/otel-agent-resources@0.0.1-releasetest1?classifier=sources
- pkg:maven/io.prometheus/otel-agent-resources@1.3.2?classifier=sources
- pkg:maven/io.prometheus/otel-agent-resources@1.3.3?classifier=sources
