- pkg:maven/dev.evo.prometheus/prometheus-kt-macosx64@0.3.0-rc-3?classifier=sources
- pkg:maven/dev.evo.prometheus/prometheus-kt-macosx64@0.3.0?classifier=sources
- pkg:maven/dev.evo.prometheus/prometheus-kt-macosx64@0.3.3?classifier=sources
