- pkg:maven/io.siddhi.extension.io.prometheus/siddhi-io-prometheus@2.0.1
- pkg:maven/io.siddhi.extension.io.prometheus/siddhi-io-prometheus@2.0.1?classifier=sources
- pkg:maven/io.siddhi.extension.io.prometheus/siddhi-io-prometheus@2.1.0
- pkg:maven/io.siddhi.extension.io.prometheus/siddhi-io-prometheus@2.1.0?classifier=sources
