- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.0.0
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.0.0-alpha-1
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.0.0-alpha-1?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.0.0-alpha-2
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.0.0-alpha-2?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.0.0-alpha-3
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.0.0-alpha-3?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.0.0-alpha-4
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.0.0-alpha-4?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.0.0-alpha-5
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.0.0-alpha-5?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.0.0-beta-1
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.0.0-beta-1?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.0.0?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.1.0
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.1.0?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.2.0
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.2.0?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.2.1
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.2.1?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.3.0
- pkg:maven/io.prometheus/prometheus-metrics-exposition-formats@1.3.0?classifier=sources
