- pkg:maven/com.telenav.kivakit/kivakit-merged-prometheus@1.4.2
- pkg:maven/com.telenav.kivakit/kivakit-merged-prometheus@1.4.2?classifier=sources
- pkg:maven/com.telenav.kivakit/kivakit-merged-prometheus@1.5.0
- pkg:maven/com.telenav.kivakit/kivakit-merged-prometheus@1.5.0?classifier=sources
