- pkg:maven/com.obsidiandynamics.fulcrum/fulcrum-docker-compose@0.37.0?classifier=sources
- pkg:maven/com.obsidiandynamics.fulcrum/fulcrum-docker-compose@0.38.0?classifier=sources
- pkg:maven/com.obsidiandynamics.fulcrum/fulcrum-docker-compose@0.39.0?classifier=sources
