- pkg:maven/com.github.jcustenborder/docker-compose-junit-extension@0.0.1.1
- pkg:maven/com.github.jcustenborder/docker-compose-junit-extension@0.0.1.1?classifier=sources
- pkg:maven/com.github.jcustenborder/docker-compose-junit-extension@0.0.1.2
- pkg:maven/com.github.jcustenborder/docker-compose-junit-extension@0.0.1.2?classifier=sources
- pkg:maven/com.github.jcustenborder/docker-compose-junit-extension@0.1.4
- pkg:maven/com.github.jcustenborder/docker-compose-junit-extension@0.1.4?classifier=sources
- pkg:maven/com.github.jcustenborder/docker-compose-junit-extension@0.1.5
- pkg:maven/com.github.jcustenborder/docker-compose-junit-extension@0.1.5?classifier=sources
- pkg:maven/com.github.jcustenborder/docker-compose-junit-extension@0.1.6
- pkg:maven/com.github.jcustenborder/docker-compose-junit-extension@0.1.6?classifier=sources
