- pkg:maven/dev.travisbrown/discipline-scalatest_0.22@1.0.0-20200123-9982f0d-NIGHTLY
- pkg:maven/dev.travisbrown/discipline-scalatest_0.22@1.0.0-20200123-9982f0d-NIGHTLY?classifier=sources
- pkg:maven/dev.travisbrown/discipline-scalatest_0.22@1.0.0-20200201-c4c847f-NIGHTLY
- pkg:maven/dev.travisbrown/discipline-scalatest_0.22@1.0.0-20200201-c4c847f-NIGHTLY?classifier=sources
- pkg:maven/dev.travisbrown/discipline-scalatest_0.22@1.0.1
- pkg:maven/dev.travisbrown/discipline-scalatest_0.22@1.0.1?classifier=sources
