- pkg:maven/org.apache.ozhera/ozhera-prometheus-agent-client@2.2.2-incubating
- pkg:maven/org.apache.ozhera/ozhera-prometheus-agent-client@2.2.2-incubating?classifier=sources
- pkg:maven/org.apache.ozhera/ozhera-prometheus-agent-client@2.2.3-incubating
- pkg:maven/org.apache.ozhera/ozhera-prometheus-agent-client@2.2.3-incubating?classifier=sources
