- pkg:maven/org.apereo.cas/config@6.0.0-RC3
- pkg:maven/org.apereo.cas/config@6.0.0-RC3?classifier=sources
- pkg:maven/org.apereo.cas/config@6.0.0-RC4
- pkg:maven/org.apereo.cas/config@6.0.0-RC4?classifier=sources
- pkg:maven/org.apereo.cas/config@6.0.1
- pkg:maven/org.apereo.cas/config@6.0.1?classifier=sources
- pkg:maven/org.apereo.cas/config@6.1.0-RC2
- pkg:maven/org.apereo.cas/config@6.1.0-RC2?classifier=sources
- pkg:maven/org.apereo.cas/config@6.1.0-RC4
- pkg:maven/org.apereo.cas/config@6.1.0-RC4?classifier=sources
- pkg:maven/org.apereo.cas/config@6.1.7
- pkg:maven/org.apereo.cas/config@6.1.7?classifier=sources
- pkg:maven/org.apereo.cas/config@6.3.3?classifier=sources
- pkg:maven/org.apereo.cas/config@6.3.4?classifier=sources
- pkg:maven/org.apereo.cas/config@6.3.5?classifier=sources
- pkg:maven/org.apereo.cas/config@6.3.6?classifier=sources
