- pkg:maven/org.apereo.cas/config@6.0.0-RC3
- pkg:maven/org.apereo.cas/config@6.0.0-RC3?classifier=sources
- pkg:maven/org.apereo.cas/config@6.0.0-RC4
- pkg:maven/org.apereo.cas/config@6.0.0-RC4?classifier=sources
- pkg:maven/org.apereo.cas/config@6.0.1
- pkg:maven/org.apereo.cas/config@6.0.1?classifier=sources
- pkg:maven/org.apereo.cas/config@6.1.0-RC2
- pkg:maven/org.apereo.cas/config@6.1.0-RC2?classifier=sources
- pkg:maven/org.apereo.cas/config@6.1.0-RC4
- pkg:maven/org.apereo.cas/config@6.1.0-RC4?classifier=sources
- pkg:maven/org.apereo.cas/config@6.1.7
- pkg:maven/org.apereo.cas/config@6.1.7?classifier=sources
- pkg:maven/org.apereo.cas/config@6.3.10?classifier=sources
- pkg:maven/org.apereo.cas/config@6.3.3?classifier=sources
- pkg:maven/org.apereo.cas/config@6.3.4?classifier=sources
- pkg:maven/org.apereo.cas/config@6.3.5?classifier=sources
- pkg:maven/org.apereo.cas/config@6.3.6?classifier=sources
- pkg:maven/org.apereo.cas/config@6.3.7?classifier=sources
- pkg:maven/org.apereo.cas/config@6.3.8?classifier=sources
- pkg:maven/org.apereo.cas/config@6.3.9?classifier=sources
- pkg:maven/org.apereo.cas/config@6.4.0?classifier=sources
- pkg:maven/org.apereo.cas/config@6.4.1?classifier=sources
- pkg:maven/org.apereo.cas/config@6.5.0?classifier=sources
- pkg:maven/org.apereo.cas/config@6.5.1?classifier=sources
- pkg:maven/org.apereo.cas/config@6.5.2?classifier=sources
- pkg:maven/org.apereo.cas/config@6.5.3?classifier=sources
- pkg:maven/org.apereo.cas/config@6.5.4?classifier=sources
- pkg:maven/org.apereo.cas/config@6.5.5?classifier=sources
- pkg:maven/org.apereo.cas/config@6.5.6?classifier=sources
- pkg:maven/org.apereo.cas/config@6.6.0?classifier=sources
- pkg:maven/org.apereo.cas/config@6.6.1?classifier=sources
- pkg:maven/org.apereo.cas/config@6.6.2?classifier=sources
- pkg:maven/org.apereo.cas/config@6.6.3?classifier=sources
