- pkg:maven/de.m3y.prometheus.exporter.fsimage/fsimage-exporter@1.0
- pkg:maven/de.m3y.prometheus.exporter.fsimage/fsimage-exporter@1.0?classifier=sources
- pkg:maven/de.m3y.prometheus.exporter.fsimage/fsimage-exporter@1.1
- pkg:maven/de.m3y.prometheus.exporter.fsimage/fsimage-exporter@1.1?classifier=sources
- pkg:maven/de.m3y.prometheus.exporter.fsimage/fsimage-exporter@1.2
- pkg:maven/de.m3y.prometheus.exporter.fsimage/fsimage-exporter@1.2?classifier=sources
- pkg:maven/de.m3y.prometheus.exporter.fsimage/fsimage-exporter@1.3
- pkg:maven/de.m3y.prometheus.exporter.fsimage/fsimage-exporter@1.3?classifier=sources
- pkg:maven/de.m3y.prometheus.exporter.fsimage/fsimage-exporter@1.4
- pkg:maven/de.m3y.prometheus.exporter.fsimage/fsimage-exporter@1.4.1
- pkg:maven/de.m3y.prometheus.exporter.fsimage/fsimage-exporter@1.4.1?classifier=sources
- pkg:maven/de.m3y.prometheus.exporter.fsimage/fsimage-exporter@1.4.2
- pkg:maven/de.m3y.prometheus.exporter.fsimage/fsimage-exporter@1.4.2?classifier=sources
- pkg:maven/de.m3y.prometheus.exporter.fsimage/fsimage-exporter@1.4?classifier=sources
