- pkg:maven/org.apache.camel.karaf/camel-micrometer-prometheus@4.7.0
- pkg:maven/org.apache.camel.karaf/camel-micrometer-prometheus@4.7.0?classifier=sources
- pkg:maven/org.apache.camel.karaf/camel-micrometer-prometheus@4.8.1
- pkg:maven/org.apache.camel.karaf/camel-micrometer-prometheus@4.8.1?classifier=sources
